spring:
  cloud:
    config:
      uri: ${CONFIG_SERVER} # bunun envirement variable ile bilgisayara tanımlanıp konulması önemlidir
  config:
    import: "configserver:"
  application:
    name: user-application