server:
  port: 8888

spring:
  application:
    name: config-server-git
  cloud:
    config:
      server:
        git:
          uri: "https://github.com/BERHANS/java11configservergit.git"
          default-label: main
          skip-ssl-validation: true
          username: BERHANS
          password: ${GIT_KEY} #github üzerinden acces token oluşturulup verilir
                                                               # bunu gite direkt böyle pushlayamayız analiz eder ve yetkisini kaldırır


