server:
  port: 9090

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: root
    url: "jdbc:postgresql://localhost:5432/TrivagoAuthDB" #jdbc:postgresql://10.28.0.32:5433/trivagoAuthDB #local host yerine ipv4 adresimizi yazdık
  jpa:                                                    # sonra değiştirip postgre sql ip adresini yazdık bulut üzerinde
    hibernate:
      ddl-auto: update

my-application:
  user-profile-end-point: "http://localhost:9092/user-profile"  # bunu buraya yazmamızın sebebi uygulama ayaktayken
                                                               # burayı değiştirirsek sistemi değiştirmiş oluruz
                                                              # uygulamayı tekrar ayağa kaldırmak gerekmez
  secret-key: "ivcJ},yuow2EM8HQB,B7kauFHoQt+;e311deZnwFbw+yD=PkPO"
  secret-key-2: ${SECRETKEY}

buraya-canımın-istedigini-yazarim:
  okuyabilirim: "bu nedir yahu?"