server:
  port: 9092

#spring:
#  data:
#    mongodb:
#      host: ${MONGO_HOST}
#      port: ${MONGO_PORT}
#      database: ${MONGO_DBNAME}
#      username: ${MONGO_USERNAME}
#      password: ${MONGO_PASSWORD}

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: UserProfileDB
      username: admin
      password: root