#server:
#  port: 9090
#
#spring:
#  datasource:
#    driver-class-name: org.postgresql.Driver
#    username: postgres
#    password: ${POSTGRES_PASSWORD}
#    url: ${POSTGRES_URL} #jdbc:postgresql://10.28.0.32:5433/trivagoAuthDB #local host yerine ipv4 adresimizi yazdık
#  jpa:                                                    # sonra değiştirip postgre sql ip adresini yazdık bulut üzerinde
#    hibernate:
#      ddl-auto: update
#
#my-application:
#  user-profile-end-point: ${USER_PROFILE_URL} # bunu buraya yazmamızın sebebi uygulama ayaktayken
#                                                               # burayı değiştirirsek sistemi değiştirmiş oluruz
#                                                              # uygulamayı tekrar ayağa kaldırmak gerekmez
#  secret-key: "ivcJ},yuow2EM8HQB,B7kauFHoQt+;e311deZnwFbw+yD=PkPO"
#  secret-key-2: ${SECRETKEY}
#
#buraya-canımın-istedigini-yazarim:
#  okuyabilirim: "bu nedir yahu?"

spring:
  cloud:
    config:
      uri: ${CONFIG_SERVER} # bunun envirement variable ile bilgisayara tanımlanıp konulması önemlidir
  config:
    import: "configserver:"
  application:
    name: auth-application
